### PR TITLE
Separate dom nodes and dom methods into 2 new files.

### LINKED ISSUE #10: Reorganizing DOM
- [x] seperate all dom manipulation into `domUpdates.js`
- [x] make sure the new file is exporting correctly using `export default` *example in write up
- [x] import the behavior where it needs to be using `import`

### LINKED ISSUE #29: DOM manipulation
- [x] DOM manipulation should be organized into its own `domUpdates.js` file. The file should look something like this:

```
// domUpdates.js

let domUpdates = {
  updateDomMethod1(){...},
  updateDomMethod2(){...},
  ...
};

export default  domUpdates;
```

- [x] Any DOM updating functionality will then be imported into other files that need them. This will create a more modular structure, and allow you to test your DOM methods 

[Refactor Tractor](https://frontend.turing.io/projects/module-2/refactor-tractor-wc.html)

### LINKED ISSUE #30: Refactor DOM manipulation into methods on an object

### PR DESCRIPTION
**Pull request by GreyMatteOr**
# [name/names of contributors]

- [x] checked functionality of the webpage
- [ ] received help from a mentor/collaborator?
- [ ] added teammates as reviewers

## Notes
* There are 2 new files in our src/ directory: dom-loader and domUpdates. They isn't any new code per sè, but rather new separate files that contain one type of thing each.

* Dom-loader is where all the initial node captures will live
* domUpdates is where any functionality that updates the web page display wil live.

These have been incorporated into the bundle.js file which is imported into the HTML using a `script` element.

## Issues Addressed
* Closes #29 
* Closes #10 
* Closes #30 

## Questions
*

## Problems or Challenges
* Hard to know if absolutely everything is still working 100%, so lets go back and check that out at some point together.

## Screenshots (if applicable)
*

### CODE REVIEW

**Comment by kathrynljackson** [comment]
I edited the PR to fix a syntax error. Just in case you get notified that I made a change!

**Review by kathrynljackson — APPROVED** [review]
Very concise organization!

**Comment by krogowsk531** [comment]
This is great refactoring!  Awesome job!

**Review by krogowsk531 — APPROVED** [review]
This is fantastic!  Awesome refactoring!

**Pull request merged**
